name: Continuous Integration

on:
  pull_request:
    branches:
      - main

jobs:
  merge_pull_request:
    runs-on: ubuntu-latest
    environment: MSoup Digital Ocean Droplet
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Install dependencies
        run: |
          cd front
          npm ci

      # - name: Test application
      #   run: npm test

      - name: Build application
        run: |
          cd front
          npm run build
      
      - name: Check the results
        run: ls /home/runner/work/tokyo-python-society-site/tokyo-python-society-site/front/out

      - name: Deploy static bundle
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          source: "/home/runner/work/tokyo-python-society-site/tokyo-python-society-site/front/out"
          target: "/"