name: Continuous Integration
author: MSoup

on:
  pull_request:
    branches:
      - main

jobs:
  build_bundle:
    runs-on: ubuntu-latest
    environment: MSoup Digital Ocean Droplet
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Install dependencies
        run: |
          cd front
          npm ci

      # - name: Test application
      #   run: npm test

      - name: Build application
        run: |
          cd front
          npm run build
      
      - name: Check the results locally
        run: ls /home/runner/work/tokyo-python-society-site/tokyo-python-society-site/front/out

      - name: Deploy static bundle to DO Droplet
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          source: "/home/runner/work/tokyo-python-society-site/tokyo-python-society-site/front/out"
          target: "test"
      
      - name: Create SSH key
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.KEY }}" > ~/.ssh/id_rsa
          echo "${{ secrets.KNOWN_HOSTS }}" > ~/.ssh/known_hosts
 
      - name: Replace current bundle
        run: ssh -i ~/.ssh/id_rsa ${{secrets.USERNAME}}@${{ secrets.HOST }} "mv /data/www/alpha /data/www/${{ github.event.repository.updated_at}}_alpha && mv /home/tps/test/github/workspace/front/out /data/www/alpha"